---
- name: Install Apache HTTP Server
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache HTTP Server
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is enabled and running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Ping each host
      ping:

    - name: Clone GitHub repository
      git:
        repo: https://github.com/ridhoalba/portofolio-web.git
        dest: /var/www/portofolio-web
        update: yes # Update the repository if it already exists

    - name: Copy Apache configuration file
      copy:
        src: /root/.jenkins/workspace/portofolio-web/ansible/file/portofolio-web.conf
        dest: /etc/apache2/sites-available/portofolio-web.conf
      notify:
        - Restart Apache

    - name: Disable default Apache site and enable portofolio-web.conf
      command: a2ensite portofolio-web.conf
      args:
        creates: /etc/apache2/sites-available/portofolio-web.conf
      notify:
        - Restart Apache

    - name: Disable default Apache site and enable portofolio-web.conf
      command: a2dissite 000-default.conf
      args:
        creates: /etc/apache2/sites-available/000-default.conf
      notify:
        - Restart Apache

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
