---
- name: Install Apache HTTP Server
  hosts: all
  become: yes
  ignore_unreachable: yes
  tasks:
    - name: Ping each host
      ping:
      ignore_errors: yes
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache HTTP Server
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is enabled and running
      service:
        name: apache2
        state: started
        enabled: yes

    # - name: mkdir
    #   shell: mkdir /var/www/portofolio-web
    - name: Clone GitHub repository
      copy:
        src: /root/.jenkins/workspace/portofolio-web/
        dest: /var/www/portofolio-web
    # Update the repository if it already exists

    - name: Copy Apache configuration file
      copy:
        src: /root/.jenkins/workspace/portofolio-web/ansible/file/portofolio-web.conf
        dest: /etc/apache2/sites-available/portofolio-web.conf
      notify:
        - Restart Apache
    - name: enable and disable
      ansible.builtin.shell:
        cmd: a2ensite portofolio-web.conf
        chdir: /etc/apache2/sites-available/

    - name: disable
      ansible.builtin.shell:
        cmd: a2dissite 000-default.conf
        chdir: /etc/apache2/sites-available/

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
