---
- name: Install Apache HTTP Server
  hosts: all
  become: yes
  tasks:
    - name: Update apt package cache
      apt:
        update_cache: yes

    - name: Install Apache HTTP Server
      apt:
        name: apache2
        state: present

    - name: Ensure Apache service is enabled and running
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Ping each host
      ping:

    - name: Copy project
      copy:
        src: /root/.jenkins/workspace/portofolio-web
        dest: /var/www/
        remote_src: yes

    - name: Copy Apache configuration file
      copy:
        src: /root/.jenkins/workspace/portofolio-web/ansible/file/portofolio-web.conf
        dest: /etc/apache2/sites-available/portofolio-web.conf
      notify:
        - Restart Apache

    - name: Disable default Apache site and enable portofolio-web.conf
      shell: |
        a2dissite /etc/apache2/sites-available/000-default.conf
        a2ensite /etc/apache2/sites-available/portofolio-web.conf

  handlers:
    - name: Restart Apache
      service:
        name: apache2
        state: restarted
